SonarCloud analysis

on:
  push:
    branches: [ "master", "main" ] # 햆쮏얧썛 main 햫햟 쒫쟳햟햢쮏, 혪햨혤 햡혰햩햨햟 햫햟향햦쒫썜덈혧혜혪 혝햟햨
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonar-check:
    name: Sonar Check
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: SonarScanner Begin
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" >> $env:GITHUB_PATH
          dotnet sonarscanner begin `
          /d:sonar.projectKey="SviatoslavOpaliuk_-" `
          /d:sonar.organization="sviatoslavopaliuk" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.opencover.reportsPaths="**/coverage.xml" `
          /d:sonar.cpd.cs.minimumTokens=40 `
          /d:sonar.cpd.cs.minimumLines=5 `
          /d:sonar.exclusions=**/bin/**,**/obj/**,**/sonarcloud.yml `
          /d:sonar.qualitygate.wait=true
        shell: pwsh
      
      - name: Restore
        # 游녢 햇먫돯뉋 햏햃행뉋 햓햃햋햍햒 .sln 햏햊했햖햇
        run: dotnet restore NetSdrClient.sln
        
      - name: Build
        # 游녢 햇먫돯뉋 햏햃행뉋 햓햃햋햍햒 .sln 햏햊했햖햇
        run: dotnet build NetSdrClient.sln -c Release --no-restore

      - name: SonarScanner End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        shell: pws
